name: flutter_js
description: A Javascript engine to use with flutter.
  It uses Quickjs on Android and JavascriptCore on IOS
version: 0.8.1
homepage: https://github.com/abner/flutter_js
repository: https://github.com/abner/flutter_js

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  http: ^1.2.2
  sync_http: ^0.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.abner.flutter_js
        pluginClass: FlutterJsPlugin
      ios:
        pluginClass: FlutterJsPlugin
      linux:
        #default_package: flutter_js_linux_win
        pluginClass: FlutterJsPlugin
      macos:
        pluginClass: FlutterJsPlugin
      # windows:
      #   default_package: flutter_js_linux_windows
      windows:
        pluginClass: FlutterJsPlugin

  assets:
    - assets/js/
